FROM quay.io/rockylinux/rockylinux:10-ubi as repos
FROM quay.io/centos-bootc/centos-bootc:stream10 as imagectl
FROM quay.io/rockylinux/rockylinux:10 as builder

RUN dnf install -y \
    podman \
    bootc \
    ostree \
    rpm-ostree \
    && dnf clean all

COPY --from=imagectl /usr/share/doc/bootc-base-imagectl/ /usr/share/doc/bootc-base-imagectl/
COPY --from=imagectl /usr/libexec/bootc-base-imagectl /usr/libexec/bootc-base-imagectl
RUN chmod +x /usr/libexec/bootc-base-imagectl

RUN rm -rf /etc/yum.repos.d/*

COPY --from=repos /etc/yum.repos.d/*.repo /etc/yum.repos.d/

COPY --from=repos /etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-10 /etc/pki/rpm-gpg

COPY rocky-10.yaml /usr/share/doc/bootc-base-imagectl/manifests/

RUN /usr/libexec/bootc-base-imagectl build-rootfs --reinject --manifest=rocky-10 /target-rootfs

###

FROM scratch

COPY --from=builder /target-rootfs/ /

LABEL containers.bootc 1
LABEL ostree.bootable 1
LABEL org.opencontainers.image.vendor Rocky Enterprise Software Foundation
LABEL org.opencontainers.image.description Rocky Linux Bootable Container Image
RUN bootc container lint --fatal-warnings
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
